### ISSUE TITLE
Timely and bigdata

### ISSUE THREAD

**Issue by kali** [frankmcsherry/timely-dataflow#15] opened 2016-01-12 21:00 UTC
Hi, 

I have a few weeks ahead of me to try and implement some bigdata/rust toolbox, and I'm trying to assess how timely could help me. 

I am toying right now with https://amplab.cs.berkeley.edu/benchmark/ , have single-host implementation for Query 1 and Query 2 and starting to put some timely in the mix (focusing on query2, query1 is too boring).

I must admit I am struggling a bit. I got it running on small datasets, but so far haven't been able to coerce it into doing things in the right order — not loading everything from disk before starting to reduce the data, in order not to overflow memory. Would you be interested in having a look and give me some insight as to what I should do ? The code is there, https://gitlab.zoy.org/kali/dx16 . The most interesting part would be https://gitlab.zoy.org/kali/dx16/blob/master/src/bin/query2_timely.rs.

I was hoping to grab you on IRC, but haven't seen you there for a while.

Thanks.

**Comment by frankmcsherry** [comment] 2016-01-12 22:51
Heyo, happy to help out.

One thing to bear in mind is that timely will give your operators a chance to run by calling in to the closure you provide, and if you read the whole input in your closure it will do just that. What you would like to do is read "just a bit", and then return control.

Since this is a pain, there is a handy [`to_stream`](https://github.com/frankmcsherry/timely-dataflow/blob/master/src/dataflow/operators/to_stream.rs) operator that takes an `I: Iterator<Item=T>` and plays it out slowly (about 256k records at a time by default, because... I don't know; feel welcome to tweak the default). It will give each other operator a chance to run each 256k records, and the way you've written your next operator it should drain all of them before returning to read more input.

If you can swing the first `unary_stream` operator you have into one that creates an owned iterator and passes that to `to_stream`, I think (hope) you'll be much happier. It might surface another pain point, but at least that is intended to do what you are looking for, I think. :D

**Comment by frankmcsherry** [comment] 2016-01-12 23:00
Another option, which I should have mentioned, is that you can also have your worker code read the input records and feed them in to the dataflow. That is, you could have the contents of your `unary_stream` operator live down where you read the filenames, and instead of pushing the filenames into the dataflow graph you could just push the records themselves at that point. This way, you would have the opportunity to call `root.step()` whenever you like (every 1,000 records, every 100,000 records).

Doing this would mean that each worker would need to look at the list of files and pick out the ones they want to process independently, which requires more careful logic than `index == 0`. But, that would also let you meter out the data more carefully. It would also let you get partial aggregates as you read out the data (perhaps using a new epoch each X records, giving aggregates for each epoch independently). Query 2 doesn't call for that, but ... it might be fun. :)

**Comment by kali** [comment] 2016-01-13 08:18
Thanks ! I had not found of calling root.step() eagerly and did not know about to_stream. I'll keep you posted.

**Comment by frankmcsherry** [comment] 2016-01-14 09:05
By the way, let me know as you make progress / have questions. I've looked at query 2 and it should be a fine fit, plus there are a bunch of neat tricks to play once you've gotten it to a point that you grok. 

I'll leave the issue open for you, but feel free to close it if you like, at any point.

**Comment by kali** [comment] 2016-01-14 15:33
I'm definitely making progress. It is now working on my laptop, and runs with about a 10% penalty on my laptop compared to my baseline in-house-mapreduce version. 

I have created specific types for my hash keys ([u8;12]) to avoid moving vec around, impl abomonation on them.

I'm now trying to run it on a three-node cluster. I could not get it to work so far, I'll come back to it later tonight or tomorrow.

Feel free to have a look at the gitlab repository. Note that query2_timely is now merged with query2 to ease benchmarking.

**Comment by kali** [comment] 2016-01-14 19:29
ok. now that i have sorted out some network issues, i have 3x16 workers up and happy.

they are so happy they start allocating stuff like crazy and get oom-killed in a few seconds, even with the smallest dataset test.

anything obvious I should be aware of about when data is send on the wire or something ?

**Comment by frankmcsherry** [comment] 2016-01-14 20:32
So, hrm. Data on the wire should be the same size as the in-memory representation (abomonation is basically just `memcpy` with pointer chasing). I've never technically tried it on a `[u8; xyz]`, but I would think it should work (as there are no pointers to chase, and  memcpy should work fine).

I'm not exactly sure, so I'll probably try and reproduce it. One thing that does come to mind is that you are technically doing something naughty in the operator methods (no reason you shouldn't have known). The lines

```rust
notif.notify_at(&RootTimestamp::new(0));
```

are being called each time the operator has a chance to run. This means the operator is continually asking for the chance to send records at time zero, independent of whether it actually has a need to send something. A more "idiomatic" (meaning: what I would have written) approach is to ditch that line, and change the record reading from

```rust
while let Some((_, data)) = input.next() { ...
```

to 

```rust
while let Some((time, data)) = input.next() {
    notif.notify_at(time);
```

which will request a notification only when the operator actually receives input data. Without this change, the workers will roughly spam each other with "progress" notifications, indicating that they have some more work to do. It's possible that this is related, but ... not clear. Let me grab the code and see what I can find! :D

**Comment by frankmcsherry** [comment] 2016-01-14 20:51
If by chance you have a set of args you like, let me know. I'm trying to track down the tiny dataset to see if the problems pop up as something obvious, but ... blah s3 etc. :)

**Comment by frankmcsherry** [comment] 2016-01-15 08:18
We worked through this, and it seems like the root cause was the use of `notify_at(..)` in a context where timely doesn't expect it, specifically in an operator execution where no input data are received. 

At the moment, this type of thing is prevented (or not) "by convention", but we do have an upcoming change where this is taken more seriously, and times are presented to logic as "capabilities", meaning a) you need one to send data at a give time, and b) you can only receive them from the system (with messages), and can't (without some effort) forge them. I think this would have prevented the issue in this case.

**Closed by frankmcsherry** 2016-01-15 08:18 UTC

**Comment by kali** [comment] 2016-02-21 14:49
Hello there,

Sorry to come back to this, I am not sure I get everything right with notifications. I isolated the timely code for query 2 here https://github.com/kali/dazone/blob/master/src/bin/query2_timely.rs . The next post in my series will explains this code, you can see a draft here: https://github.com/kali/kali.github.io/blob/master/_drafts/Query2-in-timely.md

It works, it's basically in the state we left it last time, but spamming notify_at in the input receiver feels wrong.

So I passed vec![RootTimestamp::new(0)] in the unary_notify, and stopped calling notify_at in the input handler, and it does not work. Or rather in works as in "I get the expected result", but there are still messages sent to workers which do not want them at that time:

```
21/02 15:32 ~/dev/github/dazone% cargo build && ./target/debug/query2_timely -w 8
result: 9651
thread 'worker thread 0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'worker thread 3' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
```

Code is here: https://github.com/kali/dazone/blob/notif/src/bin/query2_timely.rs 

So I'm wondering what is the role of notify_at exactly. Does it means "notify me when... " or does it means "say to the others i'm still in the middle of that" ? In the latter case, spamming it would feel less wrong, but why is it not handled by the operator generic code ? It looks to me that it should know without me calling it back.

You also implied last time making timestamp out of thin air was not right. In that case, how can/should one use the unary_notify parameter ?

**Comment by kali** [comment] 2016-02-21 14:52
On a more general note, if you find anything wrong about what I'm saying about timely, please tell me. I'll post tomorrow as usual.

https://github.com/kali/kali.github.io/blob/master/_drafts/Query2-in-timely.md

**Comment by frankmcsherry** [comment] 2016-02-21 15:09
Let's see. First, I don't see anything obvious in the code at the moment, but let me keep pondering. In the meantime, I'll try and explain notifications.

First, if you are pointed at the head of master, you should have a much harder time getting the error you are seeing. It is possible that there is a bug yet to be shaken out, and if you have a small repro I can definitely look into that (e.g. does it fail when no data are supplied); I'll try taking what you have linked and seeing if it breaks when I comment out your data.

The role of `notify_at` is two-fold: it reserves the right to send something at that time (which may or may not require communicating with other workers), and it enqueues a request that will be dequeued in a call to `next()` once that time is "complete", meaning the operator will receive no more records with that timestamp. 

Generally, requesting a notification doesn't spam the other workers, as the operator only communicates *changes* in capabilities.

You should be able to make a timestamp out of thin air, but only if you do it as you do in the constructor. This allows the operator to indicate at start-up that there is work to do. Once the computation is running, sending data for which you don't have a capability is a no-no (and is largely prevented by the new version of the code in master). It is possible that there is a glitch in the start-up logic, though this stuff has worked in the past (at least, not exploding).

**Comment by frankmcsherry** [comment] 2016-02-21 15:29
I have a local reproduction, but I'm not certain that it is notifications yet. If you don't mind, try removing the 

    while root.step() {}

line. Timely will finish out the computation for you when it exits the `execute_from_args` call. It seems like  what might be happening is that you manually call `root.step()` lots and then it gets called again post-shutdown, where (for as yet unclear reasons) some folks still have something to say. 

It is absolutely a bug, but it might be more of a "clean shut-down" bug than a notification bug.

**Comment by kali** [comment] 2016-02-21 15:30
OK. Thanks. Working with the master, I get there errors. You can check out dazone, it should compile with current rust nightly. the "notif" branch have the breaking change. The data is there: http://kalidyn.zoy.fr:35000/fbsharing/fcmV5RyZ . It's a tiny subset, but it is enough to reproduce the error. You need to tar -zxf it at the root of dazone, and then call "./target/debug/query2_timely -w 8".

If I read you right, "spamming" notify_at in the input handler is what I am expected to do in order to keep the capability to send data for the current time, and I should not worry about it as it's a light local op.

**Comment by kali** [comment] 2016-02-21 15:31
I still see the message one time out of four without the while root.step() {} (which indeed seems to be useless).

**Comment by frankmcsherry** [comment] 2016-02-21 15:47
Okies, there was absolutely a bug in the initialization logic. It seems like it might have crept in with the recent capabilities update, but let me try and explain:

When you request a capability at start-up, timely "assumes" that each instance of the operator will request the same capabilities. So, each operator instance multiplies the number of capabilities it expects are at large by `peers`. Before things shut down, it expects to hear about `peers` capabilities being disposed of.

What we were doing in the capabilities drop, though, was minting `peers` times as many capabilities, which meant that each worker actually held `peers` capabilities, and ultimately `peers * peers` capabilities are released throughout the system, which makes everything go sideways.

I've pushed a fix. If you would be willing to try it out, that would be great. My previously-always-crashing repro is now not-crashing-at-all, but it might just be that my repro broke.

**Comment by kali** [comment] 2016-02-21 16:00
yes ! looks good.  no errors with the constructor time registering with both operator in the script.

One last question if you don't mind: is RootTimestamp::new(0) the right way to forge the timestamp ? I assume what I put in the operator code have to be in sync with whatever to_stream() does

**Comment by frankmcsherry** [comment] 2016-02-21 16:06
That is correct. Technically, what `to_stream` uses is `Default::default` which is ... almost certainly bad. However, it isn't obvious how you should have discovered that (so, these aren't super user friendly yet). 

I think the "right" thing to do is probably to request the notifications in the `input.for_each` block, so that even if someone changes the upstream behavior your operator would still behave properly. Requesting notifications should be somewhat cheap (there is a de-duplication done for you, so 2nd+ notification requests get suppressed automatically).

**Comment by kali** [comment] 2016-02-21 16:25
OK, I'll put them back in the handlers. Thanks for the fix and the explanations.
